name: Laravel Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Configure MySQL Connection
      run: |
          sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/g' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/g' .env
          sed -i 's/DB_PORT=3306/DB_PORT=3306/g' .env
          sed -i 's/DB_DATABASE=database/DB_DATABASE=laravel/g' .env
          sed -i 's/DB_USERNAME=homestead/DB_USERNAME=root/g' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/g' .env
  
  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
